version: '3'
services:
db:
image: percona/percona-server:8.0
ports:
- "3306:3306"
app1:
build: ./application1
ports:
- "5001:80"
app2:
build: ./application2
ports:
- "5002:80"
nginx:
build: ./nginx
ports:
- "8080:80"
depends_on:
- app1
- app2